spring:
  datasource:
    username: root
    url: jdbc:mysql:///vhr?serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    password: 1234
server:
  port: 8083

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false